apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webrtc.backend.fullname" . }}-sip
  labels:
    {{- include "webrtc.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  SIP_USERNAME: {{ .Values.backend.env.SIP_USERNAME | quote }}
  SIP_PASSWORD: {{ .Values.backend.env.SIP_PASSWORD | quote }}
