apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webrtc.backend.fullname" . }}
  labels:
    {{- include "webrtc.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "webrtc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "webrtc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      hostNetwork: {{ .Values.backend.hostNetwork }}
      dnsPolicy: {{ .Values.backend.dnsPolicy }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
            - name: sip
              containerPort: {{ .Values.backend.sip.port }}
              protocol: UDP
          {{- with .Values.backend.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
