{{- if .Values.udpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: {{ include "webrtc.backend.fullname" . }}-sip
  labels:
    {{- include "webrtc.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  parentRefs:
    - name: {{ .Values.udpRoute.gatewayName }}
      {{- if .Values.udpRoute.gatewayNamespace }}
      namespace: {{ .Values.udpRoute.gatewayNamespace }}
      {{- end }}
      {{- if .Values.udpRoute.sectionName }}
      sectionName: {{ .Values.udpRoute.sectionName }}
      {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "webrtc.backend.fullname" . }}
          port: {{ .Values.backend.sip.port }}
{{- end }}
